spring:
  banner:
    location: classpath:/banner/banner.txt
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_udemy?useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false